package com.wearadb.ui

import androidx.compose.runtime.Composable
import androidx.compose.runtime.Immutable
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.res.stringResource
import com.wearadb.R

@Immutable
data class Strings(
    // HomeScreen
    val homeSubtitle: String,
    val sectionTools: String,
    val sectionHistory: String,
    val sectionUsbDebug: String,
    val usbDebugDesc: String,
    val featureShell: String,
    val featureShellDesc: String,
    val featureDevice: String,
    val featureDeviceDesc: String,
    val featureApps: String,
    val featureAppsDesc: String,
    val featureFiles: String,
    val featureFilesDesc: String,
    val featureAdvanced: String,
    val featureAdvancedDesc: String,
    val featureFastboot: String,
    val featureFastbootDesc: String,
    val featureUsbAdb: String,
    val featureUsbAdbDesc: String,
    val statusDisconnected: String,
    val statusConnecting: String,
    val statusAuth: String,
    val statusConnected: String,
    val statusError: String,
    val labelIp: String,
    val labelPort: String,
    val btnConnect: String,
    val btnConnecting: String,
    val btnDisconnect: String,
    val btnDiscover: String,
    val btnPair: String,
    val errorConnect: String,
    val btTitle: String,
    val btMessage: String,
    val btConfirm: String,
    val btDismiss: String,
    val actionFavorite: String,
    val actionDelete: String,
    // Shared
    val btnBack: String,
    val btnClose: String,
    val btnCancel: String,
    val btnRefresh: String,
    val btnSend: String,
    // ShellScreen
    val shellTitle: String,
    val shellSubtitle: String,
    val shellWifiFix: String,
    val shellShizuku: String,
    val shellScene: String,
    val shellBrevent: String,
    val shellHint: String,
    val shellInputHint: String,
    // DeviceInfoScreen
    val deviceInfoTitle: String,
    val infoBasic: String,
    val infoBrand: String,
    val infoModel: String,
    val infoCodename: String,
    val infoSerial: String,
    val infoSystem: String,
    val infoFingerprint: String,
    val infoScreen: String,
    val infoResolution: String,
    val infoBattery: String,
    val infoDesignCapacity: String,
    val infoCurrentCapacity: String,
    val infoBatteryType: String,
    val infoHealth: String,
    val infoBatteryLevel: String,
    val infoBatteryStatus: String,
    val infoVoltage: String,
    val infoTemperature: String,
    val infoMemStorage: String,
    val infoRam: String,
    val infoUsed: String,
    val infoAvailable: String,
    val infoTotal: String,
    val infoNoData: String,
    val infoInternalStorage: String,
    val infoNoDataRefresh: String,
    // AdvancedOpsScreen
    val advancedTitle: String,
    val opsDisplay: String,
    val opsScreenshot: String,
    val opsScreenOn: String,
    val opsScreenOff: String,
    val opsVolume: String,
    val opsVolUp: String,
    val opsVolDown: String,
    val opsVolMute: String,
    val opsConnectivity: String,
    val opsWifiOn: String,
    val opsWifiOff: String,
    val opsBtOn: String,
    val opsBtOff: String,
    val opsNavigation: String,
    val opsBack: String,
    val opsPower: String,
    val opsMedia: String,
    val opsPrev: String,
    val opsPlayPause: String,
    val opsNext: String,
    val opsRebootDevice: String,
    val opsSelectReboot: String,
    val opsRebootNormal: String,
    val opsShutdown: String,
    val opsWiredDebug: String,
    val opsFastbootMode: String,
    val screenshotSuccess: String,
    val screenshotFailed: String,
    val screenshotSave: String,
    // PairingScreen
    val pairTitle: String,
    val pairWirelessTitle: String,
    val pairStep1: String,
    val pairStep2: String,
    val pairStep3: String,
    val pairPortNote: String,
    val labelPairCode: String,
    val pairCodePlaceholder: String,
    val btnPairing: String,
    val btnPairingProgress: String,
    val pairFailed: String,
    val pairTips: String,
    val pairTip1: String,
    val pairTip2: String,
    val pairTip3: String,
    val pairTip4: String,
    val btnRetry: String,
    val manualConnectTitle: String,
    // AppsScreen
    val appsTitle: String,
    val appsInstallApk: String,
    val appsSearchHint: String,
    val appsFilterAll: String,
    val appsFilterSystem: String,
    val appsFilterThird: String,
    val appsSystemCount: (Int) -> String,
    val appsThirdCount: (Int) -> String,
    val appsDisabled: String,
    val appsActionStop: String,
    val appsActionClear: String,
    val appsActionDisable: String,
    val appsActionEnable: String,
    val appsActionUninstall: String,
    val appsPickerTimeout: String,
    // FilesScreen
    val filesTitle: String,
    val filesPushHint: String,
    val filesParent: String,
    val filesEmpty: String,
    val filesSize: (String) -> String,
    val filesPermission: (String) -> String,
    val filesModified: (String) -> String,
    val filesActionView: String,
    val filesActionPull: String,
    val filesActionInstall: String,
    val filesActionDelete: String,
    val filesContentTitle: String,
    val filesContentTooLong: (Int, Int) -> String,
    // DiscoveryScreen
    val discoveryTitle: String,
    val discoveryScanning: String,
    val discoveryStopped: String,
    val discoveryConnectable: (Int) -> String,
    val discoveryPairable: (Int) -> String,
    val discoveryEmptyTitle: String,
    val discoveryEmptyHint: String,
    val discoveryNoPair: String,
    val discoveryNoPairHint: String,
    val discoveryActionConnect: String,
    val discoveryActionPair: String,
    val btnStop: String,
    val btnScan: String,
    // FastbootScreen
    val fbModeTitle: String,
    val fbReboot: String,
    val fbRebootSystem: String,
    val fbRebootRecovery: String,
    val fbRebootBootloader: String,
    val fbPartitionOps: String,
    val fbFlashPartition: String,
    val fbErasePartition: String,
    val fbOemTitle: String,
    val fbOemExec: String,
    val fbUnlock: String,
    val fbLock: String,
    val fbAdvancedTransfer: String,
    val fbTempBoot: String,
    val fbStage: String,
    val fbFetch: String,
    val fbDeviceVars: String,
    val fbGetvarAll: String,
    val fbFlashSuccessTitle: String,
    val fbFlashSuccessMsg: (String) -> String,
    val fbStayFastboot: String,
    val fbUsbHint: String,
    val fbUsbPermission: String,
    val fbDevicesHeader: String,
    val fbEmptyHint: String,
    val fbSerial: (String) -> String,
    val fbFlashing: String,
    val fbConnectLog: String,
    val fbOemDialogTitle: String,
    val fbCmdLabel: String,
    val fbCmdPlaceholder: String,
    val fbExecute: String,
    val fbEraseTitle: String,
    val fbEraseWarning: String,
    val fbSelectPartition: String,
    val fbPartitionName: String,
    val fbManualInput: String,
    val fbEraseConfirm: String,
    val fbFlashTitle: String,
    val fbSelectImage: String,
    val fbFlashConfirm: String,
    val fbTempBootTitle: String,
    val fbTempBootWarning: String,
    val fbSelectBoot: String,
    val fbBootConfirm: String,
    val fbStageTitle: String,
    val fbStageDesc: String,
    val fbSelectUpload: String,
    val fbStageConfirm: String,
    // UsbAdbScreen extras
    val usbConnectLog: String,
    val usbDescInfo: String,
    val usbDescShell: String,
    val usbDescApps: String,
    val usbDescFiles: String,
    val usbDescAdvanced: String,
    val usbConnectedFmt: (String) -> String,
    val usbNotConnected: String,
    val usbDetectedDevices: String,
    val usbNoDeviceHint: String,
    val usbSerial: (String) -> String,
    val usbRebootFastboot: String,
    val usbRebootFastbootDesc: String,
)

@Composable
fun rememberStrings(): Strings = Strings(
    homeSubtitle = stringResource(R.string.home_subtitle),
    sectionTools = stringResource(R.string.section_tools),
    sectionHistory = stringResource(R.string.section_history),
    sectionUsbDebug = stringResource(R.string.section_usb_debug),
    usbDebugDesc = stringResource(R.string.usb_debug_desc),
    featureShell = stringResource(R.string.feature_shell),
    featureShellDesc = stringResource(R.string.feature_shell_desc),
    featureDevice = stringResource(R.string.feature_device),
    featureDeviceDesc = stringResource(R.string.feature_device_desc),
    featureApps = stringResource(R.string.feature_apps),
    featureAppsDesc = stringResource(R.string.feature_apps_desc),
    featureFiles = stringResource(R.string.feature_files),
    featureFilesDesc = stringResource(R.string.feature_files_desc),
    featureAdvanced = stringResource(R.string.feature_advanced),
    featureAdvancedDesc = stringResource(R.string.feature_advanced_desc),
    featureFastboot = stringResource(R.string.feature_fastboot),
    featureFastbootDesc = stringResource(R.string.feature_fastboot_desc),
    featureUsbAdb = stringResource(R.string.feature_usb_adb),
    featureUsbAdbDesc = stringResource(R.string.feature_usb_adb_desc),
    statusDisconnected = stringResource(R.string.status_disconnected),
    statusConnecting = stringResource(R.string.status_connecting),
    statusAuth = stringResource(R.string.status_auth),
    statusConnected = stringResource(R.string.status_connected),
    statusError = stringResource(R.string.status_error),
    labelIp = stringResource(R.string.label_ip),
    labelPort = stringResource(R.string.label_port),
    btnConnect = stringResource(R.string.btn_connect),
    btnConnecting = stringResource(R.string.btn_connecting),
    btnDisconnect = stringResource(R.string.btn_disconnect),
    btnDiscover = stringResource(R.string.btn_discover),
    btnPair = stringResource(R.string.btn_pair),
    errorConnect = stringResource(R.string.error_connect),
    btTitle = stringResource(R.string.bt_title),
    btMessage = stringResource(R.string.bt_message),
    btConfirm = stringResource(R.string.bt_confirm),
    btDismiss = stringResource(R.string.bt_dismiss),
    actionFavorite = stringResource(R.string.action_favorite),
    actionDelete = stringResource(R.string.action_delete),
    btnBack = stringResource(R.string.btn_back),
    btnClose = stringResource(R.string.btn_close),
    btnCancel = stringResource(R.string.btn_cancel),
    btnRefresh = stringResource(R.string.btn_refresh),
    btnSend = stringResource(R.string.btn_send),
    shellTitle = stringResource(R.string.shell_title),
    shellSubtitle = stringResource(R.string.shell_subtitle),
    shellWifiFix = stringResource(R.string.shell_wifi_fix),
    shellShizuku = stringResource(R.string.shell_shizuku),
    shellScene = stringResource(R.string.shell_scene),
    shellBrevent = stringResource(R.string.shell_brevent),
    shellHint = stringResource(R.string.shell_hint),
    shellInputHint = stringResource(R.string.shell_input_hint),
    deviceInfoTitle = stringResource(R.string.device_info_title),
    infoBasic = stringResource(R.string.info_basic),
    infoBrand = stringResource(R.string.info_brand),
    infoModel = stringResource(R.string.info_model),
    infoCodename = stringResource(R.string.info_codename),
    infoSerial = stringResource(R.string.info_serial),
    infoSystem = stringResource(R.string.info_system),
    infoFingerprint = stringResource(R.string.info_fingerprint),
    infoScreen = stringResource(R.string.info_screen),
    infoResolution = stringResource(R.string.info_resolution),
    infoBattery = stringResource(R.string.info_battery),
    infoDesignCapacity = stringResource(R.string.info_design_capacity),
    infoCurrentCapacity = stringResource(R.string.info_current_capacity),
    infoBatteryType = stringResource(R.string.info_battery_type),
    infoHealth = stringResource(R.string.info_health),
    infoBatteryLevel = stringResource(R.string.info_battery_level),
    infoBatteryStatus = stringResource(R.string.info_battery_status),
    infoVoltage = stringResource(R.string.info_voltage),
    infoTemperature = stringResource(R.string.info_temperature),
    infoMemStorage = stringResource(R.string.info_mem_storage),
    infoRam = stringResource(R.string.info_ram),
    infoUsed = stringResource(R.string.info_used),
    infoAvailable = stringResource(R.string.info_available),
    infoTotal = stringResource(R.string.info_total),
    infoNoData = stringResource(R.string.info_no_data),
    infoInternalStorage = stringResource(R.string.info_internal_storage),
    infoNoDataRefresh = stringResource(R.string.info_no_data_refresh),
    advancedTitle = stringResource(R.string.advanced_title),
    opsDisplay = stringResource(R.string.ops_display),
    opsScreenshot = stringResource(R.string.ops_screenshot),
    opsScreenOn = stringResource(R.string.ops_screen_on),
    opsScreenOff = stringResource(R.string.ops_screen_off),
    opsVolume = stringResource(R.string.ops_volume),
    opsVolUp = stringResource(R.string.ops_vol_up),
    opsVolDown = stringResource(R.string.ops_vol_down),
    opsVolMute = stringResource(R.string.ops_vol_mute),
    opsConnectivity = stringResource(R.string.ops_connectivity),
    opsWifiOn = stringResource(R.string.ops_wifi_on),
    opsWifiOff = stringResource(R.string.ops_wifi_off),
    opsBtOn = stringResource(R.string.ops_bt_on),
    opsBtOff = stringResource(R.string.ops_bt_off),
    opsNavigation = stringResource(R.string.ops_navigation),
    opsBack = stringResource(R.string.ops_back),
    opsPower = stringResource(R.string.ops_power),
    opsMedia = stringResource(R.string.ops_media),
    opsPrev = stringResource(R.string.ops_prev),
    opsPlayPause = stringResource(R.string.ops_play_pause),
    opsNext = stringResource(R.string.ops_next),
    opsRebootDevice = stringResource(R.string.ops_reboot_device),
    opsSelectReboot = stringResource(R.string.ops_select_reboot),
    opsRebootNormal = stringResource(R.string.ops_reboot_normal),
    opsShutdown = stringResource(R.string.ops_shutdown),
    opsWiredDebug = stringResource(R.string.ops_wired_debug),
    opsFastbootMode = stringResource(R.string.ops_fastboot_mode),
    screenshotSuccess = stringResource(R.string.screenshot_success),
    screenshotFailed = stringResource(R.string.screenshot_failed),
    screenshotSave = stringResource(R.string.screenshot_save),
    // PairingScreen
    pairTitle = stringResource(R.string.pair_title),
    pairWirelessTitle = stringResource(R.string.pair_wireless_title),
    pairStep1 = stringResource(R.string.pair_step1),
    pairStep2 = stringResource(R.string.pair_step2),
    pairStep3 = stringResource(R.string.pair_step3),
    pairPortNote = stringResource(R.string.pair_port_note),
    labelPairCode = stringResource(R.string.label_pair_code),
    pairCodePlaceholder = stringResource(R.string.pair_code_placeholder),
    btnPairing = stringResource(R.string.btn_pairing),
    btnPairingProgress = stringResource(R.string.btn_pairing_progress),
    pairFailed = stringResource(R.string.pair_failed),
    pairTips = stringResource(R.string.pair_tips),
    pairTip1 = stringResource(R.string.pair_tip1),
    pairTip2 = stringResource(R.string.pair_tip2),
    pairTip3 = stringResource(R.string.pair_tip3),
    pairTip4 = stringResource(R.string.pair_tip4),
    btnRetry = stringResource(R.string.btn_retry),
    manualConnectTitle = stringResource(R.string.manual_connect_title),
    // AppsScreen
    appsTitle = stringResource(R.string.apps_title),
    appsInstallApk = stringResource(R.string.apps_install_apk),
    appsSearchHint = stringResource(R.string.apps_search_hint),
    appsFilterAll = stringResource(R.string.apps_filter_all),
    appsFilterSystem = stringResource(R.string.apps_filter_system),
    appsFilterThird = stringResource(R.string.apps_filter_third),
    appsSystemCount = run { val f = stringResource(R.string.apps_system_count); { count: Int -> f.format(count) } },
    appsThirdCount = run { val f = stringResource(R.string.apps_third_count); { count: Int -> f.format(count) } },
    appsDisabled = stringResource(R.string.apps_disabled),
    appsActionStop = stringResource(R.string.apps_action_stop),
    appsActionClear = stringResource(R.string.apps_action_clear),
    appsActionDisable = stringResource(R.string.apps_action_disable),
    appsActionEnable = stringResource(R.string.apps_action_enable),
    appsActionUninstall = stringResource(R.string.apps_action_uninstall),
    appsPickerTimeout = stringResource(R.string.apps_picker_timeout),
    // FilesScreen
    filesTitle = stringResource(R.string.files_title),
    filesPushHint = stringResource(R.string.files_push_hint),
    filesParent = stringResource(R.string.files_parent),
    filesEmpty = stringResource(R.string.files_empty),
    filesSize = run { val f = stringResource(R.string.files_size); { s: String -> f.format(s) } },
    filesPermission = run { val f = stringResource(R.string.files_permission); { s: String -> f.format(s) } },
    filesModified = run { val f = stringResource(R.string.files_modified); { s: String -> f.format(s) } },
    filesActionView = stringResource(R.string.files_action_view),
    filesActionPull = stringResource(R.string.files_action_pull),
    filesActionInstall = stringResource(R.string.files_action_install),
    filesActionDelete = stringResource(R.string.files_action_delete),
    filesContentTitle = stringResource(R.string.files_content_title),
    filesContentTooLong = run { val f = stringResource(R.string.files_content_too_long); { shown: Int, total: Int -> f.format(shown, total) } },
    // DiscoveryScreen
    discoveryTitle = stringResource(R.string.discovery_title),
    discoveryScanning = stringResource(R.string.discovery_scanning),
    discoveryStopped = stringResource(R.string.discovery_stopped),
    discoveryConnectable = run { val f = stringResource(R.string.discovery_connectable); { count: Int -> f.format(count) } },
    discoveryPairable = run { val f = stringResource(R.string.discovery_pairable); { count: Int -> f.format(count) } },
    discoveryEmptyTitle = stringResource(R.string.discovery_empty_title),
    discoveryEmptyHint = stringResource(R.string.discovery_empty_hint),
    discoveryNoPair = stringResource(R.string.discovery_no_pair),
    discoveryNoPairHint = stringResource(R.string.discovery_no_pair_hint),
    discoveryActionConnect = stringResource(R.string.discovery_action_connect),
    discoveryActionPair = stringResource(R.string.discovery_action_pair),
    btnStop = stringResource(R.string.btn_stop),
    btnScan = stringResource(R.string.btn_scan),
    // FastbootScreen
    fbModeTitle = stringResource(R.string.fb_mode_title),
    fbReboot = stringResource(R.string.fb_reboot),
    fbRebootSystem = stringResource(R.string.fb_reboot_system),
    fbRebootRecovery = stringResource(R.string.fb_reboot_recovery),
    fbRebootBootloader = stringResource(R.string.fb_reboot_bootloader),
    fbPartitionOps = stringResource(R.string.fb_partition_ops),
    fbFlashPartition = stringResource(R.string.fb_flash_partition),
    fbErasePartition = stringResource(R.string.fb_erase_partition),
    fbOemTitle = stringResource(R.string.fb_oem_title),
    fbOemExec = stringResource(R.string.fb_oem_exec),
    fbUnlock = stringResource(R.string.fb_unlock),
    fbLock = stringResource(R.string.fb_lock),
    fbAdvancedTransfer = stringResource(R.string.fb_advanced_transfer),
    fbTempBoot = stringResource(R.string.fb_temp_boot),
    fbStage = stringResource(R.string.fb_stage),
    fbFetch = stringResource(R.string.fb_fetch),
    fbDeviceVars = stringResource(R.string.fb_device_vars),
    fbGetvarAll = stringResource(R.string.fb_getvar_all),
    fbFlashSuccessTitle = stringResource(R.string.fb_flash_success_title),
    fbFlashSuccessMsg = run { val f = stringResource(R.string.fb_flash_success_msg); { partition: String -> f.format(partition) } },
    fbStayFastboot = stringResource(R.string.fb_stay_fastboot),
    fbUsbHint = stringResource(R.string.fb_usb_hint),
    fbUsbPermission = stringResource(R.string.fb_usb_permission),
    fbDevicesHeader = stringResource(R.string.fb_devices_header),
    fbEmptyHint = stringResource(R.string.fb_empty_hint),
    fbSerial = run { val f = stringResource(R.string.fb_serial); { serial: String -> f.format(serial) } },
    fbFlashing = stringResource(R.string.fb_flashing),
    fbConnectLog = stringResource(R.string.fb_connect_log),
    fbOemDialogTitle = stringResource(R.string.fb_oem_dialog_title),
    fbCmdLabel = stringResource(R.string.fb_cmd_label),
    fbCmdPlaceholder = stringResource(R.string.fb_cmd_placeholder),
    fbExecute = stringResource(R.string.fb_execute),
    fbEraseTitle = stringResource(R.string.fb_erase_title),
    fbEraseWarning = stringResource(R.string.fb_erase_warning),
    fbSelectPartition = stringResource(R.string.fb_select_partition),
    fbPartitionName = stringResource(R.string.fb_partition_name),
    fbManualInput = stringResource(R.string.fb_manual_input),
    fbEraseConfirm = stringResource(R.string.fb_erase_confirm),
    fbFlashTitle = stringResource(R.string.fb_flash_title),
    fbSelectImage = stringResource(R.string.fb_select_image),
    fbFlashConfirm = stringResource(R.string.fb_flash_confirm),
    fbTempBootTitle = stringResource(R.string.fb_temp_boot_title),
    fbTempBootWarning = stringResource(R.string.fb_temp_boot_warning),
    fbSelectBoot = stringResource(R.string.fb_select_boot),
    fbBootConfirm = stringResource(R.string.fb_boot_confirm),
    fbStageTitle = stringResource(R.string.fb_stage_title),
    fbStageDesc = stringResource(R.string.fb_stage_desc),
    fbSelectUpload = stringResource(R.string.fb_select_upload),
    fbStageConfirm = stringResource(R.string.fb_stage_confirm),
    // UsbAdbScreen extras
    usbConnectLog = stringResource(R.string.usb_connect_log),
    usbDescInfo = stringResource(R.string.usb_desc_info),
    usbDescShell = stringResource(R.string.usb_desc_shell),
    usbDescApps = stringResource(R.string.usb_desc_apps),
    usbDescFiles = stringResource(R.string.usb_desc_files),
    usbDescAdvanced = stringResource(R.string.usb_desc_advanced),
    usbConnectedFmt = run { val f = stringResource(R.string.usb_connected_fmt); { name: String -> f.format(name) } },
    usbNotConnected = stringResource(R.string.usb_not_connected),
    usbDetectedDevices = stringResource(R.string.usb_detected_devices),
    usbNoDeviceHint = stringResource(R.string.usb_no_device_hint),
    usbSerial = run { val f = stringResource(R.string.usb_serial); { serial: String -> f.format(serial) } },
    usbRebootFastboot = stringResource(R.string.usb_reboot_fastboot),
    usbRebootFastbootDesc = stringResource(R.string.usb_reboot_fastboot_desc),
)

val LocalStrings = staticCompositionLocalOf<Strings> {
    error("No Strings provided")
}
